spring:
#  mvc:
#    static-path-pattern: /res/**
  web:
#    resources:
#      add-mappings: true
    resources:
      static-locations: [classpath:/pictures/]

  mvc:
    hiddenmethod:
      filter:
        enabled: true