server:
  port: 8001
spring:
  application:
    name: nacos-payment-provider #注册到Nacos的服务名
  cloud:
    nacos: # 客户端注册的地址
      server-addr: localhost:8848
      username: nacos
      password: nacos
#      discovery: #命名空间 可以做项目隔离
#        namespace: car-namespace
#        group: dev # 在命名空间下的组别，可以用来做细粒度的隔离
#Endpoint 本身对外界隐藏显示，我们需要在配置里面开启对 Endponit 的显示支持。
#对外界保留那些 Endpoint，若是所有则使用* ；
management:
  endpoints:
    web:
      exposure:
        include: '*'

