server:
  port: 8003
spring:
  application:
    name: nacos-order-consumer #注册到Nacos的服务名
  cloud:
    nacos: # 客户端注册的地址
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        register-enabled: false #默认为true，只订阅，不注册自己则为false
    openfeign:
      httpclient:
        ok-http:
          read-timeout:

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-payment-provider
